Added ellipse
Gordon01/rugui pull request #4
Opened 2022-02-09 09:14 UTC by ROCKFAL1

Added ellipse to library and it's example to emulator

2022-02-13 13:45 UTC, Gordon01 requested changes
Thank you for PR, but it needs some polish!

2022-02-13 13:45 UTC, Gordon01 commented on emulator/.gitignore
> +target
This shouldn't be needed, but even if it is, the root .gitignore should be edited.

2022-02-13 13:45 UTC, Gordon01 commented on rugui/src/geometry.rs
> +    pub fn new(width: u32, height: u32, center: Vec2, color: Color) -> Self {
Can we merge the code from Circle and Ellipse and reuse it as much as we can?
Currently, `Circle::new()`, `Circle::from_bbox()` and `Circle::filled()` are almost identical to the Ellipse ones.

2022-02-13 13:45 UTC, Gordon01 commented on rugui/src/geometry.rs
> +}
Most codebases add empty lines at the end of every file.

2022-02-13 13:45 UTC, Gordon01 commented on rugui/src/geometry.rs
> +        if self.height >= self.width {
`self.height.min(self.width)`
should do the job

2022-02-13 13:45 UTC, Gordon01 commented on rugui/src/geometry.rs
> +        self.thickness = t;
`self.thickness = t.min(self.max_thickness());`
or something like that

2022-02-14 07:07 UTC, ROCKFAL1 commented on rugui/src/geometry.rs
> +        self.thickness = t;
Fixed

2022-02-15 20:08 UTC, merged